User authentication
Hilyas68/tasks-manager pull request #1
Opened 2024-05-29 11:21 UTC by Naomiel

Account activation for users

2024-05-30 18:35 UTC, Hilyas68 requested changes

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/controller/EmailSendController.java
> +@RequestMapping("api/v1/mail")
is `EmailSendController` needed? if No, please remove it.

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/controller/ExceptionController.java
> +public class ExceptionController {
suggestion: can you rename this to `ExceptionHandler` maybe?
you can also create another package called exception and add it there.

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/controller/StaffController.java
> +        User user1 = optionalUser.get();
Can you move this logic into the `userService.createStaff()` method?
do all checks in there. Call the repository to check if the user is an Admin or not. In that case you will only inject `userService` in the controller

```The responsibility of the controller, is to accept a request, invoke the processing, and respond according to the result of the processing.```

I believe this apply to other controllers to

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/security/JWTUtil.java
> +            throw new InvalidTokenRequestException("JWT", token, errorMessage);
you're throwing this exception but didn't handle it in your `@ControllerAdvice`

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/serviceImpl/UserServiceImpl.java
> +            throw new RuntimeException("Email already exist");
do you want to create a custom exception say `EmailAlreadyExistException` or a generic one `ApplicationException` then handle it in you controllerAdvice.

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/serviceImpl/UserServiceImpl.java
> +        return null;
might not be a good idea to always return null in your application

2024-05-30 18:35 UTC, Hilyas68 commented on src/main/resources/application-dev.properties
> +spring.datasource.password=Glor!ous26
can you pick secrets from environment variable instead. some like
spring.datasource.password=${DB_PASSWORD}

2024-05-31 09:18 UTC, Hilyas68 requested changes

2024-05-31 09:18 UTC, Hilyas68 commented on pom.xml
> +			<version>8.0.33</version>
it will be nice to putt all your version within the `<properties>` tag

2024-05-31 09:18 UTC, Hilyas68 commented on pom.xml
> +		<plugins>
try to format your code

2024-05-31 09:18 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/serviceImpl/UserServiceImpl.java
> +        Optional<UserRole> optionalUserRole = userRoleRepository.findById(user1.getRole().getId());
you can actually extracted this into a different method say `isAdmiinUser()` to just check if it's an admin user so you reduce the responsibility if createStaff method.

2024-05-31 09:18 UTC, Hilyas68 commented on src/main/java/com/accelerex/tasks_manager/serviceImpl/UserServiceImpl.java
> +        String activationLink = "http://localhost:8082/api/v1/users/activate?email=" + staffDto.getEmail();
also extract this one to `sendActivationEmail()`

2024-05-31 09:32 UTC, NkanorJ reviewed
Confirm if you can see this message

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/config/AppConfig.java
> +//    public PasswordEncoder getPasswordEncoder(){
You can remove the comment

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/StaffController.java
> +    public StaffController(UserService userService) {
You do not need a constructor

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/StaffController.java
> +@RestController
Include @RequiredArg..........

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/StaffController.java
> +    public ResponseEntity<User> createStaff(@RequestBody StaffDto staffCreationDto) {
You do not return a model in your controller, extract what you need into a response. Same with your requestbody, dtos are meant for service and not controller.

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/StaffController.java
> +        User createdStaff = userService.createStaff(staffCreationDto);
Jav17 uses var, you can use that to hide the object or datatype:  "var createdStaff = userService.createStaff(staffCreationDto);"

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/UserController.java
> +    public UserController(UserService userService) {
same here, remove constructor and include @Required.........

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/UserController.java
> +    @PostMapping("/")
If there is no endpoint simple use @PostMapping without parenthesis

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/controller/UserController.java
> +        if (user != null) {
I would advise you check is null first like 

return (Objects.isNull(user)) ? ResponseEntity.notFound().build() : ResponseEntity.ok(user);

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/dto/UserDto.java
> +public class UserDto {
You can try utilising records instead of class for dtos

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/model/auth/User.java
> +import javax.persistence.*;
Try not to have wildcard, to avoid importing unnecessary imports

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/security/JWTUtil.java
> +        // todo: reduce the expirationTime to the barest minimum say 5 mins.
Best practice, your code should explain what is happening, try not to explain using comments

2024-05-31 09:32 UTC, NkanorJ commented on src/main/java/com/accelerex/tasks_manager/config/AppConfig.java
> +//        return new BCryptPasswordEncoder();
testing

2024-06-03 15:41 UTC, closed without merging